### ISSUE TITLE
Repo contains a password

### ISSUE THREAD

**Issue by LordOfTheRats** [m23project/m23-devel#1]
Hi there,

just to let you know that Google pointed me to this file, which contains a clear text password: https://github.com/m23project/m23-devel/blob/master/m23/inc/vncpasswd.php

Best wishes

**Comment by m23project** [comment]
Hi,

it's a password that is generated randomly when installing the m23-vbox package. So it's not a security flaw, but a piece of garbage in the repo.

I've added vncpasswd.php to .gitignore to make it not be included in the next upload.

Thanks for reporting :-)

Hauke
